module.exports = {
  SERVICE_TOKEN: process.env.REACT_APP_SERVICE_TOKEN,
  TEMPLATE_TOKEN: process.env.REACT_APP_TEMPLATE_TOKEN,
  PUBLIC_KEY: process.env.REACT_APP_PUBLIC_KEY,
  RECAPTCHA_TOKEN: process.env.REACT_APP_RECAPTCHA_TOKEN,
};
